### PR TITLE
fix: ISF chart Y-axis formatting for mmol/L units

### LINKED ISSUE #557: ISF setup in onboarding: the chart axis is displayed with mg/dL values also when importing mmol ISF
ISF setup in onboarding: the chart axis is displayed with mg/dL values also when importing mmol ISF settings from NS. 

Image

Exists in current dev. 

## Attach a Log
*Tap the Trio settings icon at the bottom of the screen, then tap 'Share logs' on the bottom of the list and attach it to this ticket.*

## To Reproduce
*Steps to reproduce the behavior:*
1. *Go to '...'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

## Expected behavior
*A clear and concise description of what you expected to happen.*

## Screenshots
*If applicable, add screenshots to help explain your problem.*

### Smartphone:
* Hardware: *[e.g. iPhone 15 Pro]*
* OS Version: *[e.g. iOS 17.5]*

### Pump:
* Manufacturer: *[e.g. Insulet]*
* Model: *[e.g. Omnipod Dash or Eros]*

### CGM:
* Device: *[e.g. Dexcom G7]*
* Manager app: *[e.g. Dexcom App or xDrip4iOS]*

### Trio Version:
* Version Number: *[e.g. 1.9.2]*
* Repo: *nightscout/trio*
* Git Reference: *[e.g. commit hash]*

## Technical Details
*If applicable, provide any technical details that might help in diagnosing the problem. This could include logs, error messages, or relevant configuration details.*

## Additional context
*Add any other context about the problem here.*

### PR DESCRIPTION
**Pull request by Sjoerd-Bo3**
## Summary
- Fixes incorrect Y-axis label formatting in ISF chart during onboarding for mmol/L users
- Resolves #557

## Problem
When importing ISF settings from Nightscout during onboarding, the chart Y-axis labels were not properly formatted for users with mmol/L units. The values were displayed without appropriate decimal places.

## Solution
Updated the Y-axis label formatting in `InsulinSensitivityStepView.swift` to use the existing `numberFormatter` which correctly formats values based on the selected units:
- mmol/L: Shows 1 decimal place (e.g., "2.8")  
- mg/dL: Shows no decimal places (e.g., "50")

The chart scale remains dynamic and adjusts to the data range automatically.

## Test plan
- [ ] Test onboarding with mmol/L units selected
- [ ] Import ISF settings from Nightscout  
- [ ] Verify chart Y-axis shows values with 1 decimal place
- [ ] Test with mg/dL units to ensure no regression
- [ ] Verify chart still scales dynamically based on ISF values

### CODE REVIEW

File: Trio/Sources/Modules/Onboarding/View/OnboardingSteps/TherapySettings/InsulinSensitivityStepView.swift [hunk 1]
```diff
@@ -188,8 +188,12 @@ struct InsulinSensitivityStepView: View {
                 .addingTimeInterval(60 * 60 * 24)
         )
         .chartYAxis {
-            AxisMarks(values: .automatic(desiredCount: 4)) { _ in
-                AxisValueLabel()
+            AxisMarks(values: .automatic(desiredCount: 4)) { value in
```
Comment (dnzxy) [inline Trio/Sources/Modules/Onboarding/View/OnboardingSteps/TherapySettings/InsulinSensitivityStepView.swift:199]: Unnecessary change.
The previous code should do the exact same implicitely.

**Review by dnzxy — CHANGES_REQUESTED** [review]

**Comment by dnzxy** [comment]
@Sjoerd-Bo3 please remove code as requested in the PR review comment, then let's get this over the line. Thanks :)

**Comment by dnzxy** [comment]
@Sjoerd-Bo3 Please make the requested change to this PR, so we can get this shipped.
I will leave this up until Sunday, December 14. If there is still no progress on it by then, I will close this as stale.

File: Trio/Sources/Modules/Onboarding/View/OnboardingSteps/TherapySettings/InsulinSensitivityStepView.swift (hunk 1 above)
Comment (MikePlante1) [reply Trio/Sources/Modules/Onboarding/View/OnboardingSteps/TherapySettings/InsulinSensitivityStepView.swift:199]: I merged this PR on top of dev (0.6.0.26) and it does fix the y-axis. I then deleted the rest of PR and only kept the change on line 140, and the y-axis was still fixed. So I agree this part looks unecessary.

@Sjoerd-Bo3, if you're too busy but don't disagree with @dnzxy, I can add a commit to revert this section and just keep the line 140 change.

**Review by dnzxy — APPROVED** [review]
Initially commented on here that a in the `AxisMarks` callback was an unnecessary signature change, but on a closer look this is required to apply the unit-aware number formatter to the axis labels. I reckon _that_ fixes the mmol/L formatting issue, so this change makes sense after all.

Approving + merging.
