### PR TITLE
Code fixes and Improvements Garmin Manager & Config

### LINKED ISSUE #994: FEAT/GARMIN: [UX] Watch app display settings have inconsistent element alignment
Describe the bug
The display settings within the Garmin watch app have inconsistent, seemingly random alignment — UI elements shift from one side of the screen to the other depending on which option is selected. This creates a visually unstable experience that feels unpolished and would be a blocker for merging feat/garmin into the main dev branch.

Current behavior:
Tapping different options within the Watch App Settings within Garmin App Settings page causes elements to reposition inconsistently — left-aligned in some states, right-aligned in others, with no clear visual logic.

Expected behavior:
All display setting elements should follow a consistent alignment pattern (left or center) regardless of which option is selected.

To Reproduce
Open Trio Settings
Tap Devices → Garmin
Navigate to watch app display settings
Tap through the available options
Observe UI elements shifting alignment between selections

Expected behavior
Display settings elements should maintain consistent, stable alignment across all option states. No element should reposition based on user selection unless there is an intentional, logical reason to do so.

Screenshots
Image
Image

Setup Information
Smartphone:
Hardware: iPhone 11 Pro Max
OS Version: 26.3

Pump:
Manufacturer: Omnipod
Model: Dash

CGM:
Device: Dexcom G7
Manager app: Dexcom App

Trio Version:
Version Number: v0.6.0.43 (1) feat/garmin 97c76f7
Repo: nightscout/Trio/tree/feat/garmin

Additional context
Consistent alignment is a baseline UI quality requirement. Resolving this — alongside the Garmin navigation UX fix — would bring the feat/garmin branch closer to a state where it has parity with the Apple Watch implementation and is ready to be considered for merge into main.

@mountrcg

### PR DESCRIPTION
**Pull request by mountrcg**
Fixes #994, #996

## Improved the Garmin manager
Moved Core Data object fetching to occur within the `perform` block, ensuring proper thread confinement and Sendable compliance.

## Couple of improvements for Config UX/UI
- Confirmation dialog for automatic watchface data re-enablement after watchface change
Simulator Screenshot - Dev 16 Pro - 2026-03-31 at 20 51 06

- fix spacing and list row dividers
- shorten watch app names to prevent line breaks

### CODE REVIEW

File: Trio/Sources/Models/GarminWatchSettings.swift [hunk 1]
```diff
@@ -35,9 +35,9 @@ enum GarminSecondaryAttributeChoice: String, JSON, CaseIterable, Identifiable, C
     var displayName: String {
         switch self {
         case .tbr:
-            return String(localized: "TBR (Temp Basal Rate)", comment: "")
+            return String(localized: "TBR", comment: "")
         case .eventualBG:
-            return String(localized: "Eventual BG", comment: "")
+            return String(localized: "evBG", comment: "")
```
Comment (dnzxy) [inline Trio/Sources/Models/GarminWatchSettings.swift:40]: We don't use "BG" for anything that isn't actually blood glucose.
Plus abbreviations like this one are not really good.
Can we please stick with `Eventual Glucose` and possibly ´Temp Basal´ (Rate?) above?

File: Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift [hunk 2]
```diff
@@ -8,6 +8,7 @@ struct WatchConfigGarminAppConfigView: View {
     @State private var shouldDisplayHint3: Bool = false
     @State private var shouldDisplayHint4: Bool = false
     @State var hintDetent = PresentationDetent.large
+    @State private var showWatchfaceSwitchConfirmDialog: Bool = false
```
Comment (dnzxy) [inline Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift]: We try to have boolean variables begin with `should…`

File: Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift [hunk 3]
```diff
@@ -210,6 +224,8 @@ struct WatchConfigGarminAppConfigView: View {
                 hintLabel: "Choose Garmin Datafield",
                 hintText: Text(
                     "Choose which datafield on your Garmin device you wish to provide data for. The datafield can be used independently from the watchface selection.\n\n" +
+                        "• Trio – The original Trio datafield, developed by Pierre.\n" +
```
Comment (dnzxy) [inline Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift:227]: Is this necessary or helpful?
Rather explain what either watchfield displays.

File: Trio/Sources/Models/GarminWatchSettings.swift [hunk 4]
```diff
@@ -87,9 +87,9 @@ enum GarminDatafield: String, JSON, CaseIterable, Identifiable, Codable, Hashabl
     var displayName: String {
         switch self {
         case .trio:
-            return String(localized: "Trio original", comment: "")
+            return String(localized: "Trio", comment: "")
```
Comment (dnzxy) [inline Trio/Sources/Models/GarminWatchSettings.swift:90]: Are these names any helpful or descriptive?
What's the difference?

**Comment by marv-out** [comment]
Just looking at the Core Data part it looks good code wise

File: Trio/Sources/Models/GarminWatchSettings.swift (hunk 1 above)
Comment (mountrcg) [reply Trio/Sources/Models/GarminWatchSettings.swift:40]: done

File: Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift (hunk 2 above)
Comment (mountrcg) [reply Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift]: done

File: Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift (hunk 3 above)
Comment (mountrcg) [reply Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift:227]: Well there are two watchfaces available in CIQ, that's how I named them. I am pretty carefree what they are named, we can change that later may be, if there are better suggestions.

File: Trio/Sources/Models/GarminWatchSettings.swift (hunk 4 above)
Comment (mountrcg) [reply Trio/Sources/Models/GarminWatchSettings.swift:90]: see above

File: Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift (hunk 3 above)
Comment (dnzxy) [reply Trio/Sources/Modules/WatchConfig/View/WatchConfigGarminAppConfigView.swift:227]: Alright, then let's please address this in a follow-up PR and change this so the watchface names make sense and especially the descriptions make sense.
